Sprint1/step2
NautroKazenaki/react-burger-sprint-1 pull request #2
Opened 2022-12-03 16:19 UTC by NautroKazenaki

2022-12-03 18:55 UTC, ArslanDev666 requested changes
## Code Review

Здравствуйте!

Отличная работа.

### **Вы молодец!**

- Теперь ингредиенты приходят от сервера;

- В приложении есть модальные окна;

### **Но есть несколько замечаний, которые нужно исправить:**

- Поправьте работу с propTypes (отметил места в коде).

- Поправьте работу с сервером (отметил места в коде).

### **Сделает код лучше:**

- Разместите контент по центру. https://yadi.sk/d/GcgkeK4Cci6QzA. И также, хедер должен быть на всю ширину.

- Также заметил несколько слов написанных с ошибками. Чтобы это происходило реже, попробуйте попользоваться расширением spell checker. https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker

### **_Подробно эти и более мелкие замечания, отмечены в коде._**

2022-12-03 18:55 UTC, ArslanDev666 commented on src/api/api.js
> +export const burgerIngredientsDataURL = 'https://norma.nomoreparties.space/api/ingredients'
**Надо исправить:** 

имена констант принято записывать в стиле UPPER_CASE

2022-12-03 18:55 UTC, ArslanDev666 commented on src/components/App/App.jsx
> +  const [state, setState] = useState({burgerIngredientsData: []});
**Можно лучше:**

Почему бы не использовать просто сразу массив, а не делать из этого объект.

```js
const [state, setState] = useState([]);
```

2022-12-03 18:55 UTC, ArslanDev666 commented on src/components/App/App.jsx
> +    const getburgerIngredientsData = () => {
**Надо исправить:**
Добавьте проверку ответа сервера - res.ok:

Например:

```
.then(res => res.ok ? res.json() : res.json().then((err) => Promise.reject(err));
```

иначе сейчас, если сервер ответит не кодом 2xx, а какой либо ошибкой (4xx, 5xx) мы не попадем в catch т.к. в этом случае fetch не выбрасывает ошибку, мы попытаемся отрисовать данные, хотя они не пришли, в итоге на попытке отрисовки несуществующих данных упадет все приложение

[https://learn.javascript.ru/fetch](https://learn.javascript.ru/fetch)

[https://developer.mozilla.org/en-US/docs/Web/API/Response/ok](https://developer.mozilla.org/en-US/docs/Web/API/Response/ok)

Т.к. эта проверка нужна у всех запросов, лучше вынести её в отдельную функцию

```js
const checkResponse = (res) => {
  return res.ok ? res.json() : res.json().then((err) => Promise.reject(err));
};
```

`fetch(someUrl).then(checkResponse)`

**Можно лучше**

в дальнейшем добавятся ещё запросы к бэкенду и лучше вынести описание этих запросов в функции. А также проверку ответа с сервера.

Например:

```js
function getIngredients() {
   return fetch(`${NORMA_API}/ingredients`)
    .then(проверка ответа)
}

```

и разместить их в отдельном файле  `utils/burger-api.js`, а не описывать запросы в самом компоненте

2022-12-03 18:55 UTC, ArslanDev666 commented on src/components/App/App.jsx
> +  console.log(state)
**надо исправить:**

В приложении не должно быть console.log, или debugger.

2022-12-03 18:55 UTC, ArslanDev666 commented on src/components/Modal/ModalWindow.jsx
> +        return (e) => {
**Можно лучше:**

не совсем понимаю зачем тут e.

2022-12-03 18:55 UTC, ArslanDev666 commented on src/components/Modal/ModalWindow.jsx
> +    const closeModalWindow = (e) => {
**Можно лучше:**

Лучше занести в функцию useEffect. Чтобы ссылка на функцию не пересоздавалась при ререндере.

2022-12-03 18:55 UTC, ArslanDev666 commented on src/components/Modal/ModalWindow.jsx
> +const ModalWindow = (props) => {
**Надо исправить:**

Для этого компонента, также следует описать пропсы.

2022-12-03 18:55 UTC, ArslanDev666 commented on src/components/Modal/ModalWindowOverlay.jsx
> +const ModalWindowOverlay = (props) => {
**Надо исправить:**

Для этого компонента, также следует описать пропсы.

2022-12-03 18:55 UTC, ArslanDev666 commented on src/components/OrderDetails/OrderDetails.jsx
> +          </div>
**надо исправить:**

Кнопка закрытия, а также title, должен быть в компоненте модального окна. Так будет легче контролировать их поведение.

2022-12-03 18:55 UTC, ArslanDev666 commented on src/components/IngredientDetails/IngredientsDetails.jsx
> +                        <C c={c}/>
**Надо исправить:**

Здесь и далее, не стоит разделять этот компонент на более мелкие, тем более таким способом.

2022-12-03 18:55 UTC, ArslanDev666 commented on src/components/IngredientDetails/IngredientsDetails.jsx
> +    debugger
**Надо исправить:**

В приложении не должно быть debbuger-ов, или логов

2022-12-03 18:55 UTC, ArslanDev666 commented on src/components/IngredientDetails/IngredientsDetails.jsx
> +const IngredientsDetails = (props) => {
**Надо исправить:**

Для этого компонента, также нужно описать propTypes.

2022-12-03 18:55 UTC, ArslanDev666 commented on src/components/BurgerIngredients/Bun.jsx
> +  props: PropTypes.arrayOf(bunTypes.isRequired).isRequired,
**Надо исправить:**

неверно описаны PropTypes для компонента, советую обратиться за помощью к наставнику.

2022-12-03 18:55 UTC, ArslanDev666 commented on src/components/BurgerIngredients/BurgerIngredients.jsx
> +  props: PropTypes.arrayOf(ingredientTypes.isRequired).isRequired,
**Надо исправить:**

Неверно описаны propTypes для компонента. 
Вы описали пропс `props`, а не `data`.

2022-12-03 18:55 UTC, ArslanDev666 commented on src/components/BurgerIngredients/BurgerIngredientsTabs.jsx
> +    <div style={{ display: "flex" }}>
**Надо исправить:**

Старайтесь не использовать инлайн стили, лучше создайте дополнительный класс и используйте его.

2022-12-03 18:55 UTC, ArslanDev666 commented on src/components/BurgerIngredients/MainIngredient.jsx
> +MainIngredient.propTypes = {
**Надо исправить:**

Аналогичная проблема как и в `BurgerIngredients`.

2022-12-03 18:55 UTC, ArslanDev666 commented on src/components/BurgerIngredients/Sause.jsx
> +Sause.propTypes = {
**Надо исправить:**

Аналогичная проблема как и в `BurgerIngredients`.

2022-12-03 18:55 UTC, ArslanDev666 commented on src/components/BurgerConstructor/BurgerConstructor.jsx
> +  debugger
**Надо исправить:**

В приложении не должно быть debuuger-ов.

2022-12-03 18:55 UTC, ArslanDev666 commented on src/components/BurgerConstructor/BurgerConstructor.jsx
> +  console.log({data})
**Надо исправить:**
Здесь и далее.
В приложении не должно быть консоль логов.

2022-12-03 18:55 UTC, ArslanDev666 commented on src/components/BurgerConstructor/BurgerConstructor.jsx
>    BurgerConstructor.propTypes = {
**Надо исправить:**

Лучше описывать propTypes за пределами компонента.

2022-12-03 18:55 UTC, ArslanDev666 commented on src/utils/PropTypes.js
> +  export const bunTypes = PropTypes.shape({
Надо исправить:

Здесь и далее. 

1. Не забывайте указывать .isRequired, без этого не будут проверяться пропсы. Также не забудьте перед отправкой работы проверить консоль в браузере на ошибки. 

2. Не стоит описывать пропсы таким образом, нам ну нужно тут дополнительно указывать что это объект ~~PropTypes.shape()~~. А также перенесите пропсы в сами компоненты, т.к. они нигде не переиспользуются.

2022-12-04 18:57 UTC, ArslanDev666 requested changes
## Code Review

Здравствуйте!

Отличная работа.

### **Вы молодец!**

- Практически все замечания с прошлого ревью были исправлены.

### **Но есть ещё несколько замечаний, которые нужно исправить:**

- Поправьте работу с propTypes, ошибки в консоли: https://yadi.sk/d/N9-5aiIcC0aU2w0.

- По макету у булок не должно быть этого элемента: https://yadi.sk/d/2cutc_CIwp5F4g.

Не исправлены следующие замечания: 

  - https://github.com/NautroKazenaki/react-burger-sprint-1/pull/2#discussion_r1038818730;
  - https://github.com/NautroKazenaki/react-burger-sprint-1/pull/2#discussion_r1038819043;
  - https://github.com/NautroKazenaki/react-burger-sprint-1/pull/2#discussion_r1038819469;

**Не забудьте перед отправкой работы проверить консоль в браузере на ошибки.**

### **Сделает код лучше:**

- Разместите контент по центру. https://yadi.sk/d/GcgkeK4Cci6QzA. И также, хедер должен быть на всю ширину.

### **_Подробно эти и более мелкие замечания, отмечены в коде._**

2022-12-04 18:57 UTC, ArslanDev666 commented on src/components/Modal/ModalWindow.jsx
> +    props: PropTypes.func
**Надо исправить:**

пропсы описаны неправильно. Нужно описывать поля которые передаются в качестве пропсов.
```js
ModalWindow.PropTypes = {
    onClose: PropTypes.func.isRequired,
    children: PropTypes.element.isRequired
}
```

И не забывайте указывать `.isRequired`, без этого пропсы не будут проверяться.

Советую ещё раз прочесть документацию.
https://ru.react.js.org/docs/typechecking-with-proptypes.html

2022-12-04 18:57 UTC, ArslanDev666 commented on src/components/Modal/ModalWindowOverlay.jsx
> +     ModalWindowOverlay.propTypes = {
**Надо исправить**

Аналогичное замечание что и в ModalWindow.

А также, стоит вынести за пределы компонента.

2022-12-04 18:57 UTC, ArslanDev666 commented on src/components/IngredientDetails/IngredientsDetails.jsx
> +      };
**Надо исправить**

Аналогичное замечание что и в ModalWindow.

А также, стоит вынести за пределы компонента.

2022-12-04 18:57 UTC, ArslanDev666 commented on src/components/IngredientDetails/IngredientsDetails.jsx
> +    const c = props.ingredient.calories
**Можно лучше:**

Лучше сразу используйте пропсы, а не создавайте отдельные переменные.

2022-12-04 18:57 UTC, ArslanDev666 commented on src/components/BurgerIngredients/MainIngredient.jsx
> +  props: {
**Надо исправить:**

вам не нужно тут (и в других местах) дополнительно делать вложенность.
А также вы неправильно описали типы пропсов. Ниже правильный вариант.
Также переименовал `mains` в `ingredient`.
```js
MainIngredient.propTypes = {
    ingredient: ingredientTypes.isRequired,
    onOpen: PropTypes.func.isRequired
}
```

2022-12-04 18:57 UTC, ArslanDev666 commented on src/components/BurgerIngredients/Sause.jsx
> +  }
**Надо исправить:**

Описал проблему в `MainIngredient`.

2022-12-04 18:57 UTC, ArslanDev666 commented on src/components/BurgerIngredients/BurgerIngredients.jsx
> +            <Sause sauses={sause} key={sause.id} onOpen={burgerIngredientModalWindowShow} />
**Можно лучше:**

Здесь и ниже, у вас повторяется вёрстка ингредиентов, поэтому можно просто сделать 1 общий компонент, а не делать разные `Sause`,`MainIngredient`.

2022-12-04 20:17 UTC, NautroKazenaki commented on src/components/OrderDetails/OrderDetails.jsx
> +          </div>
Простите, я не понимаю, зачем нужно вставлять это как надстройку в другое место. Если там должно по задумке находиться название всплывающего окна + кнопка его закрытия, то они находятся ровно там, где и должны быть. Не понимаю, почему мое виденье не имеет место быть.

2022-12-04 20:20 UTC, ArslanDev666 commented on src/components/OrderDetails/OrderDetails.jsx
> +          </div>
Дело в том, что эти элементы будут дублироваться во всех модальных окнах) ну как минимум в 2 точно))

2022-12-05 04:18 UTC, ArslanDev666 approved these changes
## Code Review

Здравствуйте!

Отличная работа.

### **Вы молодец! Работа принята. Удачи в дальнейшем обучении.**

- Практически все замечания с прошлого ревью были исправлены.

### **Также рекомендую исправить следующие замечания:**

- Лучше описывать propTypes за пределами компонента.

- Поправить вёрстку всего приложения, ещё раз пройдитесь по макету. (где-то не сходятся шрифты, где-то ширина, и т.д.)

- Исправить ошибку propTypes в консоли https://yadi.sk/d/II5AhVmWDcgoOg.

### **_Подробно эти и более мелкие замечания, отмечены в коде._**

2022-12-08 19:00 UTC, merged