Sprint2/step2
NautroKazenaki/react-burger-sprint-1 pull request #4
Opened 2022-12-17 16:04 UTC by NautroKazenaki

2022-12-17 17:03 UTC, randomroot requested changes
**Доброго времени суток!** ☀️ 🌙 

Вы провели хорошую работу по добавлению DnD и Redux в ваш проект, правильно организовали файловую структуру, добавили все необходимые экшены и action creators, сбрасываете состояние, используете удобную библиотеку для выбора активного таба, **так держать** 👍

Тем не менее, для успешной сдачи работы вам необходимо внимательно ознакомиться с комментариями, оставленными в рамках ревью и провести необходимые **изменения**, обратив **особое внимание** на следующие моменты:

- Не удается перетащить новую булку в конструктор, всегда остаётся зафиксированной та, что выбрана по-умолчанию;
- При попытке переноса элемента внутри конструктора перемещается всегда самый первый элемент на выбранную позицию (см. https://disk.yandex.ru/i/NFgjsEO0hoPpGg);
- Каждый React компонент следует разместить в своей папке, поддерживая соответствие "директория = компонент + стили (если есть)";
- Если добавить второй такой же ингредиент в конструктор и затем попробовать перетащить на него первый, то произойдет бесконечное создание их копий в конструкторе (см. https://disk.yandex.ru/i/osr3-kJiniQHsg)
- Согласно документации, функция filter возвращает копию массива, поэтому самостоятельно не следует её создавать дополнительно;
- После отладки места остановы дебаггера следует удалять (`debugger`);

Также, в рамках ревью были предложены **улучшения** вашего кода, которое могут повысить его качество, исправить возможные проблемы в будущем и углубить ваше значение по курсу.

---

Перед повторной сдачей, пожалуйста, убедитесь в том, что проект работает **корректно** и **полностью**, согласно условиям задания и чек-листу, а в консоли браузера и в консоли вашей IDE **нет ошибок** и присутствует **минимально** возможное кол-во **предупреждений**. Работа будет принята **только** после исправления всех комментариев с меткой "Надо исправить". 

---

_Если у вас возникнут вопросы относительно комментариев к коду - пишите их в соответствующем треде или передайте их через вашего куратора. Обязательно найдём самое лучшее решение :)_

**Успешного вам рефакторинга, хорошего настроения и отличных выходных!** 🐈

2022-12-17 17:03 UTC, randomroot commented on package.json
> +    "@reduxjs/toolkit": "^1.9.1",
🟡 **Можно улучшить:**

Библиотека не используется в рамках проекта, поэтому её можно безопасно удалить из зависимостей

2022-12-17 17:03 UTC, randomroot commented on src/Context/dataContext.js
> +export const dataContext = React.createContext(null)
🔴 **Нужно исправить:**

В рамках данного этапа вместо контекста Реакта используется Redux, поэтому данный файл следует удалить

2022-12-17 17:03 UTC, randomroot commented on src/components/App/App.jsx
> +      {burgerIngredientsData.length > 0 && (
🟡 **Можно улучшить:**

Имеет смысл ориентироваться на комбинацию `isLoading` и `hasError`, т.к. формально пустой ответ с сервера это не ошибка

2022-12-17 17:03 UTC, randomroot commented on src/services/reducers/burgerConstructorDataReducer.js
> +    buns: [],
🔴 **Нужно исправить:**

Т.к. в рамках конструктора может существовать только один вид булки, то следует использовать здесь единичный объект для значения ключа, вместо массива. Начальное значение целесообразно задать через `null` или `undefined`

2022-12-17 17:03 UTC, randomroot commented on src/services/reducers/burgerConstructorDataReducer.js
> +                nonBunIngredients: [...state.nonBunIngredients.filter((ingredient) => ingredient.id !== action.id)]
🔴 **Нужно исправить:**

Согласно документации, функция `filter` возвращает копию массива, поэтому самостоятельно не следует её создавать дополнительно (см. https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Array/filter)

2022-12-17 17:03 UTC, randomroot commented on src/services/actions/orderDetailsDataActions.js
> +    nonBunIngredients.push(bun);
🟡 **Можно улучшить:**

Можно упростить: [bun, ...nonBunIngredients, bun]

2022-12-17 17:03 UTC, randomroot commented on src/services/actions/orderDetailsDataActions.js
> +   console.log(burgerIngredientsId)
🟡 **Можно улучшить:**

Логгирование очень полезно на этапе разработки, однако, при сдаче работы следует эти моменты удалить из кода, чтобы в консоли было минимальное количество информационных сообщений и легче было отлавливать ошибки после "выхода в релиз" :)

2022-12-17 17:03 UTC, randomroot commented on src/services/actions/burgerConstructorDataActions.js
> +    debugger
🔴 **Нужно исправить:**

После отладки места остановы дебаггера следует удалять

2022-12-17 17:03 UTC, randomroot commented on src/components/BurgerIngredients/BurgerIngredients.jsx
> +  const [current, setCurrent] = React.useState("one");
🟡 **Можно улучшить:**

Варианты значения стейта имеет смысл вынести в отдельные константы или объединить под одной константой, чтобы их было удобно переиспользовать в рамках файла и при необходимости изменить содержимое только в одном месте, вместо множества, например:
```typescript
const Tabs = {
  BUN: 'bun',
  SAUCE: 'sauce'
  ...
}

... = useState(Tabs.BUN)
```

2022-12-17 17:03 UTC, randomroot commented on src/components/BurgerIngredients/BurgerIngredients.jsx
> +            <Bun buns={bun} key={bun._id} onOpen={showModalWindow} />
🟡 **Можно улучшить:**

Компоненты `Bun`, `Sauces` и `Mains` целесообразно объединить в один единый, например `IngredientCategory`, т.к. код и функционал у них фактически одинаковый, чтобы уменьшить дублирование

2022-12-17 17:03 UTC, randomroot commented on src/components/BurgerIngredients/MainIngredient.jsx
> +      buns.map((element) => {
🔴 **Нужно исправить:**

В `mainIngredients` не может попасть булка, т.к. уже произведена фильтрация по типу выше

2022-12-17 17:03 UTC, randomroot commented on src/components/BurgerConstructor/BurgerConstructor.jsx
> +      return sum.reduce((acc, curr) => curr.type === 'bun' ? acc  + curr.price * 2 : acc + curr.price, 0);
🟡 **Можно улучшить:**

1) Можно использовать `useMemo` для мемоизации полученного значения (см. https://ru.reactjs.org/docs/hooks-reference.html#usememo);
2) Создавать новый массив необязательно, достаточно просчитать на основе `nonBunIngredients`, взяв в качестве начального значения удвоенную стоимость булки

2022-12-17 17:03 UTC, randomroot commented on src/components/BurgerConstructor/BurgerConstructor.jsx
> +  console.log(buns)
🟡 **Можно улучшить:**

Целесообразно убрать логгирование, используемое на этапе разработки и отладки, чтобы уменьшить кол-во информации, которое выводится в консоль :)

2022-12-17 17:03 UTC, randomroot commented on src/components/BurgerConstructor/BurgerConstructor.jsx
> +      debugger
🔴 **Нужно исправить:**

По окончании отладки следует убрать точки остановы отладчика

2022-12-17 17:03 UTC, randomroot commented on src/components/BurgerIngredients/MainIngredient.jsx
> +}, [nonBunIngredients, buns])
🟡 **Можно улучшить:**

Подсчёт кол-ва элементов, добавленных в конструктор осуществляется правильно, однако не совсем оптимально, по причине того, что для каждого ингредиента осуществляется полный проход по всему массиву ингредиентов в поиске совпадающих. Если считать, что длина массива = N, то сложность данного алгоритма в целом для всех элементов = O(N*N), что при большом количестве элементов может ухудшать производительность вашего проекта.

Для оптимизации данного процесса имеет смысл рассмотреть альтернативный путь подсчёта, например проводить его в сторе, храня значения счётчиков там в отдельном объекте и изменяя его показатели при каждом добавлении/удалении элемента. Таким образом, вычислительная сложность уменьшается до O(1), т.к. сложность процесса вычисления не будет зависеть от размера массива.

О вычислительной сложности можно прочитать например здесь: https://tproger.ru/articles/computational-complexity-explained/

2022-12-18 14:03 UTC, NautroKazenaki commented
> * Если добавить второй такой же ингредиент в конструктор и затем попробовать перетащить на него первый, то произойдет бесконечное создание их копий в конструкторе (см. https://disk.yandex.ru/i/osr3-kJiniQHsg)

Шеф, совсем не понимаю, как это можно исправить, подскажите, пожалуйста

2022-12-18 21:39 UTC, randomroot requested changes
**Здравствуйте!**

Вы успешно внесли множество изменений и улучшений в ваш проект, **так держать,** однако остались несколько моментов, которые следует также **исправить** для сдачи проекта в данном спринте:

- Т.к. в рамках конструктора может существовать только один вид булки, то следует использовать здесь **единичный объект** для значения ключа, вместо массива. Начальное значение целесообразно задать через null или undefined;
- Реакт компоненты `Error` и `Loader` следует держать именно **в папке components;**
- В заказе отправляются **пустые значения** на местах булок (см. https://disk.yandex.ru/i/FZ1TbK2bLdfbwQ);
- Следует исправить установку **начального значения булки**, заменив хук и скорректировав множественные вызовы экшенов _(см. Bun.jsx);_
- К вашему вопросу о **клонировании ингредиентов в конструкторе** при перетаскивании:
    - В качестве ключа при маппинге элементов в `BurgerConstructorElementContainer` (20 строка) используйте `id`, который вы уже генерируете в рамках экшена добавления элементов, вместо `_id`, поставляемый с компонентом и не являющийся уникальным в рамках массива элементов с одинаковыми ингредиентами :)
  -  В экшн в самом начале попадает значение `dragIndex === undefined` (см. https://disk.yandex.ru/i/yZDez1Za4sk67g), вызванное тем, что индекс отсутствует в объекте `ingredient` изначально. Исправить это можно если в `useDrag` указать параметр `item` и задать `() => { return { ...ingredient, index: i } }`, - так вы установите индекс по-умолчанию  из пропсов и передадите его в `hover` в `useDrop` ниже;

**Желаю вам хорошего дня!**  🐈

2022-12-18 21:39 UTC, randomroot commented on src/utils/Error.jsx
> +const Error = () => {
🔴 **Нужно исправить:**

Реакт компоненты следует держать именно в папке `components`

2022-12-18 21:39 UTC, randomroot commented on src/utils/Loader.jsx
> +const Loader = () => (
🔴 **Нужно исправить:**

Реакт компоненты следует держать именно в папке `components`

2022-12-18 21:39 UTC, randomroot commented on src/components/BurgerConstructor/BurgerConstructor.jsx
> +   React.useMemo(() => addIngredient(bunsInitialState, dispatch), [bunsInitialState])
🔴 **Нужно исправить:**

1) `useMemo` служит для запоминания **значений** и изменяется при изменении массива зависимостей. Для отработки **действий** при изменении массива следует использовать `useCallback` (см. https://beta.reactjs.org/apis/react/useCallback)

2) Обратите внимание, что `bunsInitialState` вычисляется при каждом рендере, а из-за этого вызывается и установка стейта при каждом рендере (см. https://disk.yandex.ru/i/Ug2__zdS5hXIFA). Для установки начального значения вычисление `bunsInitialState` следуете перенести **внутрь** функции хука

2022-12-18 21:39 UTC, randomroot commented on src/components/BurgerIngredients/Bun.jsx
> +    currentBun.map((bun) => {
🔴 **Нужно исправить:**

Если `currentBun` пусто, то произойдет ошибка при обращении к переменной (см. логи https://disk.yandex.ru/i/t2blE8mAJ5JS-w). Следует добавить проверку на наличие значения

2022-12-18 21:39 UTC, randomroot commented on src/services/actions/orderDetailsDataActions.js
> +     nonBunIngredients.unshift(bun);
🔴 **Нужно исправить:**

Т.к. `bun` сейчас у вас массив, то `unshift` добавить внутрь не один элемент, а массив, как в примере - см. https://disk.yandex.ru/i/3AcsjVZATAIefQ. Вследствие чего функция `map` далее отработает неправильно и вернёт для массивов `null`

2022-12-19 00:03 UTC, NautroKazenaki commented on src/components/BurgerConstructor/BurgerConstructor.jsx
> +   React.useMemo(() => addIngredient(bunsInitialState, dispatch), [bunsInitialState])
Уф, мне тяжело дается использование хуков, которые я прежде не использовал. И с добавлением useCallback - вовсе не происходит вызова функции. Все остальные необходимые изменения я произвел. Спасибо вам огромное!

2022-12-19 07:30 UTC, randomroot commented on src/components/BurgerConstructor/BurgerConstructor.jsx
> +   React.useMemo(() => addIngredient(bunsInitialState, dispatch), [bunsInitialState])
Прошу прощения, ошибся, правильный хук - `useEffect` (см. https://reactjs.org/docs/hooks-effect.html)

2022-12-19 12:43 UTC, randomroot approved these changes
🟢 **Работа принята:**

Все необходимые правки были внесены, код улучшен согласно рекомендациям, критических замечаний больше не имеется, **так держать**👍

Перед слитием PR в ветку `main` рекомендую воспользоваться автоматическим форматированием кода, это сильно экономит время, а Ваш код будет всегда красив. Одно из наиболее популярных дополнений для форматирования кода - Prettier (https://prettier.io/). Также обратите внимание на дополнительный комментарий к вопросу о хуках.

Очень хорошая работа, **желаю вам хорошего дня и успехов в дальнейшем обучении**! 🐈

![cat](https://media.giphy.com/media/CjmvTCZf2U3p09Cn0h/giphy-downsized.gif)

2023-01-01 10:26 UTC, merged