Sprint3/step1
NautroKazenaki/react-burger-sprint-1 pull request #5
Opened 2023-01-07 18:56 UTC by NautroKazenaki

2023-01-07 23:34 UTC, randomroot requested changes
**Доброго времени суток!** ☀️ 🌙 

Вы неплохо справились с задачей добавления роутинга и авторизации в ваш проект, хорошая верстка новых страниц и организация проекта, выполнен корректно компонент `ProtectedRoute`, интересный экран с 404 ошибкой и сюрпризом внутри, юмор в коде приветствуется, продолжайте в том же духе 👍 

Тем не менее, для успешной сдачи работы вам необходимо внимательно ознакомиться с комментариями, оставленными в рамках ревью и провести необходимые **изменения**, обратив особое внимание на следующие моменты:

- Заказы, согласно заданию, могут делать только авторизованные пользователи, следует проверять этот момент и перенаправлять на логин, если пользователь еще не авторизован;
- При отправке заказа следует указывать хедер `Authorization` с токеном пользователя;
- При нажатии по ссылкам в хедере осуществляется полный переход с перезагрузкой страницы, вследствие использования классических ссылок, следует заменить их на компоненты `Link` или `NavLink` из пакета `react-router`;
- Для булок не осуществляется переход по ссылке на роут `ingredients/{id}` (https://disk.yandex.ru/i/dv3T2SPPWnShpg);
- При прямом переходе по роуту `ingredients/{id}` следует открывать страницу с информацией об ингредиенте (https://disk.yandex.ru/i/3ir7Tv1505eDeQ);
- В компоненте `Bun`, пока не выбрана текущая булка значение `currentBun` будет равно `null` и будет возникать ошибка при исполнении (https://disk.yandex.ru/i/ZklqxuoxFakG3Q);
- Т.к. в проекте сейчас две обертки `Router` - в `App.jsx` и `index.js`, то навигация работает некорректно (следует удалить первую из `App.jsx`);
- Роуты `/login`, `/register`, `/forgot-password` и `/reset-password` следует сделать недоступными для авторизованных пользователей;
- При нажатии кнопки "Отмена" следует скрывать кнопки "Отмена" и "Сохранить" в Профиле;
- Кнопки "Отмена" и "Сохранить" следует отображать только, если пользователь изменил данные в форме;
- При запросах использующих `accessToken` следует проверять ответ сервера. Если время жизни токена истекло, то выполняется запрос обновления токена и повторяется запрос, который не был выполнен успешно;
- В шапке панели навигации следует сделать активной ту ссылка на маршрут, где сейчас находится пользователь. Ссылка остаётся активной, если пользователь попадает на вложенные динамические маршруты. (https://disk.yandex.ru/i/pLZsbcGF-1Llag);
- При переходе на экран "История заказов" следует отображать пустой экран с переключением бокового меню, вместо 404 ошибки;

Также, в рамках ревью были предложены **улучшения** вашего кода, которое могут повысить его качество, исправить возможные проблемы в будущем и углубить ваше значение по курсу, в том числе:

- При появлении ошибок в API после отправки форм рекомендуется любым удобным для вас методом оповещать об этом пользователя, чтобы он был в курсе ситуации и знал, что ему необходимо исправить;
- Имеет смысл привести к дизайну отображение кнопок "Сохранить" и "Отменить";
- Постарайтесь использовать автоматическое форматирование, это сильно экономит время, а Ваш код будет всегда красив. Одно из наиболее популярных дополнений для форматирования кода - Prettier (https://prettier.io/);

---

Перед повторной сдачей, пожалуйста, убедитесь в том, что проект работает **корректно** и **полностью**, согласно условиям задания и чек-листу, а в консоли браузера и в консоли вашей IDE **нет ошибок** и присутствует **минимально** возможное кол-во **предупреждений**. Работа будет принята **только** после исправления всех комментариев с меткой "Надо исправить". 

---

**Успешного вам рефакторинга, хорошего настроения и отличного дня!** 🐈

2023-01-07 23:34 UTC, randomroot commented on src/components/AppHeader/AppHeader.jsx
> +      <a href="/" className={headerStyles.headerConstructorLinkContainer}>
🔴 **Нужно исправить:**

Вместо обычных ссылок следует использовать `Link` или `NavLink` (предпочтительнее) из пакета `react-router` (см. https://v5.reactrouter.com/web/guides/primary-components/navigation-or-route-changers)

2023-01-07 23:34 UTC, randomroot commented on src/components/Page404/Page404.jsx
> +                    <img src="https://assets.codepen.io/5647096/backToTheHomepage.png" />
🟡 **Можно улучшить:**

Картинки или файлы со внешних сайтов целесообразно сохранять у себя локально, чтобы быть точно уверенным, что они не пропадут и находятся под вашим контролем

2023-01-07 23:34 UTC, randomroot commented on src/components/Profile/ProfilePage.jsx
> +                    <Button  htmlType="submit" disabled={(username.length > 0 && email.length > 0) ? false : true}>
🟡 **Можно улучшить:**

Можно заменить тернарный оператор на выражение `={!(username.length > 0 && email.length > 0)}` или `{username.length === 0 || email.length === 0}`

2023-01-07 23:34 UTC, randomroot commented on src/components/ResetPassword/ResetPasswordPage.jsx
> +            {!isUser && (
🟡 **Можно улучшить:**

**Здесь и далее по коду** - такие редиректы имеет смысл вынести чуть выше в отдельный `if`, чтобы не осуществлять рендеринг всего остального содержимого страницы:

```js
if (!isUser) {
 return ( /*код редиректа*/ )
}

return (
// код страницы
)

2023-01-07 23:34 UTC, randomroot commented on src/components/App/App.jsx
> +      <Router >
🔴 **Нужно исправить:**

Следует убрать Router из данного компонента, т.к. он уже есть у вас в `index.jsx` и сейчас получается у вас два роутера, которые мешают друг другу и некорректно обрабатывают навигацию в приложении

2023-01-12 11:27 UTC, randomroot requested changes
**Здравствуйте!**

Вы успешно внесли множество изменений и улучшений в ваш проект, так держать, однако остались несколько моментов, которые следует также **исправить** для сдачи проекта в данном спринте:

- Для булок не осуществляется переход по ссылке на роут `ingredients/{id}` (https://disk.yandex.ru/i/dv3T2SPPWnShpg);
- При прямом переходе по роуту `ingredients/{id}` следует открывать страницу с информацией об ингредиенте (https://disk.yandex.ru/i/3ir7Tv1505eDeQ);
- При нажатии кнопки "Отмена" следует скрывать кнопки "Отмена" и "Сохранить" в Профиле;
- Кнопки "Отмена" и "Сохранить" следует отображать только, если пользователь изменил данные в форме;
- Заготовку истории заказов следует расположить по пути `/profile/orders`, т.к. она отличается от "Ленты заказов";
- При запросах использующих `accessToken` следует проверять ответ сервера. Если время жизни токена истекло (это определяется обычно по коду ответа 401 или 403, либо по информационному сообщению, в котором упоминается `expired`), то выполняется запрос обновления токена (через метод API `refresh`), а затем повторяется исходный запрос, который не был выполнен успешно;

**Можно улучшить:**

- Для элемента "Выход" в профиле имеет смысл выставить курсор `pointer`, чтобы визуально подчеркнуть его кликабельность;
- Между кнопкой "Войти" и ссылками на регистрацию лучше добавить небольшой отступ, как в дизайне (https://disk.yandex.ru/i/uw829jLv18soJQ);

**Хорошего вам дня и настроения!** 🐈

2023-01-12 11:27 UTC, randomroot commented on src/components/App/App.jsx
> +      {/* <Router > */}
🟡 **Можно улучшить:**

Неиспользуемый код имеет смысл удалять из файлов, чтобы поддерживать чистоту кода. В случае необходимости его восстановления можно воспользоваться средствами Git-a.

2023-01-12 11:27 UTC, randomroot commented on src/components/BurgerIngredients/Bun.jsx
> +         if (currentBun !== null) {
🟡 **Можно улучшить:**

Можно упростить до одного условного оператора: 
```js
if (currentBun !== null && currentBun._id === props.buns._id)
```

2023-01-12 11:27 UTC, randomroot commented on src/components/ForgotPassword/ForgotPasswordPage.jsx
> +            {isAuth && (
🟡 **Можно улучшить:**

**Здесь и для других страниц**, на которые не должен попадать пользователь, если он авторизирован, не дублируйте в каждой странице эту логику, а лучше создать либо отдельный компонент `OnlyUnAuthRoute`, по аналогии c `ProtectedRoute`, который будет защищать эти страницы от авторизированных пользователей или доработать компонент `ProtectedRoute`, передавая дополнительный параметр, определяющий в каком режиме работает компонент - только для авторизированных пользователей или только для неавторизированных пользователей, например

```js 
const ProtectedRoute = ({ children, path, onlyUnAuth = false }) => {
```
если установлен флаг `onlyUnAuth`  в пропсах - то значит переданный `path` доступен только неавторизированным пользователям, иначе он доступен только авторизированным пользователям

2023-01-12 11:27 UTC, randomroot commented on src/components/IngredientDetails/IngredientsDetails.jsx
> +    <>
🟡 **Можно улучшить:**

Данную конструкцию можно заменить на два `return`:

```jsx

if (!ingredient) {
  return null;
}

return ( 
 <>
   <div ...
)
```

Такой код обычно легче воспринимается и уходит необходимость в дополнительном React.Fragment :)

2023-01-12 11:27 UTC, randomroot commented on src/components/IngredientDetails/IngredientsDetails.jsx
> +   let ingredient = data.find(item => item._id === ingredientId)
🔴 **Нужно исправить:** 

В данной конструкции получается, что вы сначала устанавливаете значение переменной, а на следующей строке его сразу перезаписываете, возможно первое действие является лишним:

```js
let ingredient = clickedIngredient;
if (ingredient === null) {
 ingredient = data.find(...)
}
```
или через константу:
```js
const ingredient = clickedIngredient || data.find(...)
```

2023-01-12 16:41 UTC, NautroKazenaki commented
Добрый вечер! Сейчас запушу фиксы, но, к сожалению, совсем не понимаю, что делать с этими двумя пунктами для булок. Они реализованы 1в1 как все остальные ингредиенты, но конкретно с ними не выходит по каким-то причинам.

> * Для булок не осуществляется переход по ссылке на роут `ingredients/{id}` (https://disk.yandex.ru/i/dv3T2SPPWnShpg);
> * При прямом переходе по роуту `ingredients/{id}` следует открывать страницу с информацией об ингредиенте (https://disk.yandex.ru/i/3ir7Tv1505eDeQ);

Реализовал через костыль, но тут тоже не хватает опыта, чтобы полноценно реализовать функционал.

> * При нажатии кнопки "Отмена" следует скрывать кнопки "Отмена" и "Сохранить" в Профиле;
> * Кнопки "Отмена" и "Сохранить" следует отображать только, если пользователь изменил данные в форме;

Подскажите, пожалуйста
:(
> * При запросах использующих `accessToken` следует проверять ответ сервера. Если время жизни токена истекло (это определяется обычно по коду ответа 401 или 403, либо по информационному сообщению, в котором упоминается `expired`), то выполняется запрос обновления токена (через метод API `refresh`), а затем повторяется исходный запрос, который не был выполнен успешно;

2023-01-12 22:28 UTC, randomroot commented
@NautroKazenaki, добрый день!

**1.1.** У булок есть отличие:

![image](https://user-images.githubusercontent.com/15111821/212186577-17e6df25-de74-4907-ae51-5e6bc765de74.png)

Метод `preventDefault` блокирует (пропускает) вызов события ссылки, поэтому переход на роут не осуществляется.

**1.2.** Приношу извинения, здесь не совсем корректно описал проблему. Прямой переход по ссылке **работает**, однако в коде не совсем корректно расположен блок, где описано открытие модального окна при переходе по ссылке. Его следует вынести за пределы `Switch` и тогда при прямом переходе оно будет открываться:

![image](https://user-images.githubusercontent.com/15111821/212193431-4b8f4640-6cbf-4597-b566-f7c527823e43.png)

**2**

Для работы с методами в которых используется токен можно применить следующую практику (пример не полный, попробуйте дополнить его своим кодом), воспользовавшись дополнительной универсальной функцией:

```js

export const fetchWithRefresh = async (url, options) => {
  try {
   // вызываем основной запрос
    const res = await fetch(url, options);
   // проверяем ответ
    return await checkResponse(res);
  } catch (err) {
    // если выскакивает ошибка, то проверяем, протух ли токен:
    if (err.message === "jwt expired") {
     // вызываем метод
      const refreshData = await refreshToken();
     ...
     // здесь проверяем результат и записываем токен к себе 
     ...

     // обновляем accessToken в основном запросе
      options.headers.authorization = refreshData.accessToken;
     
      ...
      // повторяем вызов основного запроса
      ...
    } else {
      // если ошибка иная, то пробрасываем её дальше
      return Promise.reject(err);
    }
  }
};

```

2023-01-13 16:41 UTC, randomroot requested changes
**Добрый день!**

Осталось еще несколько моментов, которые следует исправить до завершения работы над спринтом, указанные в комментариях к ревью.

Также обратите внимание на ответ на заданные вами вопросы по поводу предыдущих пунктов.

**Хороших вам выходных!** 🐈

2023-01-13 16:41 UTC, randomroot commented on src/components/Profile/ProfilePage.jsx
> +                    {isInputsValueChanged && <div><Button  htmlType="submit" disabled={username.length === 0 || email.length === 0} style={{marginRight: "50px"}} >
🔴 **Нужно исправить:**

Инлайновые стили следует использовать только в крайних случаях, когда другими методами не получается задать стилизацию объекта, следует перенести такие стили в CSS файлы в отдельные классы и задавать именно имя класса в пропс.

2023-01-13 16:41 UTC, randomroot commented on src/components/Profile/ProfilePage.jsx
> +const isInputsValueChanged =
🔴 **Нужно исправить:**

1)
![image](https://user-images.githubusercontent.com/15111821/212371569-eb6cc792-35ef-4e5b-8c1e-d5a48c0bd74d.png)

`profileInfo.user` изначально равен `undefined`, поэтому приложение вылетает с ошибкой

2) Если ввести новый пароль, то кнопки не появляются

2023-01-13 16:41 UTC, randomroot commented on src/services/actions/userActions.js
> +        dispatch(fetchWithRefresh())
🔴 **Нужно исправить:**

В данную функцию следует передать `url` и объект `options` из fetch выше

2023-01-13 19:36 UTC, NautroKazenaki commented
@randomroot, безумно вас люблю и уважаю за всё ваше терпение и отзывчивость, но это какой-то ужас, damn. Когда это всё кончится, скажите, куда перевести на шаверму и колу
я ничего не понимаю
:(

2023-01-13 20:13 UTC, randomroot commented
@NautroKazenaki, смотрите, давайте разберемся с рефрешем **на примере получения данных пользователя.**

Обращаю ваше внимание `debugger` точки - перед сдачей следует их убрать :)

---

У вас есть метод `setUserInfo`. Он отвечает за запрос к API. Так как в нём содержится токен, то есть шанс, что он может вернуться к нам с ошибкой 401 или 403 с текстом `jwt expired`, что означает истечение времени его жизни. На скриншоте ниже показан исходный вызов вами `fetch`.

![image](https://user-images.githubusercontent.com/15111821/212404982-ca6a87d8-8633-4f9d-9903-684b0b1014d0.png)

В то же время вы совершенно верно добавили функцию `fetchWithRefresh` которая должна в таких случаях заменить исходный `fetch` добавив ему возможность обновления токена. 

![image](https://user-images.githubusercontent.com/15111821/212405889-6029455d-868c-4666-a25a-3e26a80e9c01.png)

Как вы можете увидеть, её параметры совпадают с параметрами `fetch`, поэтому **в первую очередь** делаем замену здесь и убираем блок `finally` ниже:

![image](https://user-images.githubusercontent.com/15111821/212406448-4481d06a-b410-415e-94cb-6c61d2db58f5.png)

**Вторым этапом** следует исправить саму функцию `fetchWithRefresh`:

![image](https://user-images.githubusercontent.com/15111821/212407365-5b3e8bdf-eedf-4b0b-945e-d9fe153af1f7.png)

**В итоге** мы получаем следующую схему:

![image](https://user-images.githubusercontent.com/15111821/212410022-b6412707-d62f-42c4-a5bf-5bcb3e46ad6e.png)

которую следует использовать и для других методов, где вы указываете хедер `Authorization`.

---

Попробуйте, если не получается - будем разбирать дальше, главное что бы вы поняли и научились технике - а дальше всё пойдет как по маслу 👍 

![image](https://thumbs.gfycat.com/IdioticInfamousEagle-max-1mb.gif)

2023-01-13 20:39 UTC, NautroKazenaki commented
@randomroot, появилось новая проблема, что данные перестали сетаться после логина. Т.е. сам логин проходит, но стейт пустой, хотя, к примеру, если делать заказ, то он узнает пользователя

2023-01-13 21:23 UTC, randomroot commented
@NautroKazenaki 

1) Т.к. в методе `fetchWithRefresh` уже содержится проверка запроса на успех, то его повторная в рамках функции `setUserInfo` приводит к ошибке, следует убрать её там:

![image](https://user-images.githubusercontent.com/15111821/212420819-908e5f7e-744b-425a-90d0-ba998d3963dc.png)

2) Добавить статус `isAuth` при установке данных пользователя:

![image](https://user-images.githubusercontent.com/15111821/212421829-f35a7acb-b180-4b80-983e-a702c7e59ba5.png)

Тогда и после логина и после перезагрузки страницы всё будет работать корректно

2023-01-13 21:33 UTC, NautroKazenaki commented
@randomroot, да, всё супер. 
Можно пушить в практикум?

2023-01-13 21:41 UTC, randomroot commented
@NautroKazenaki да, можно, утром ознакомлюсь тогда

2023-01-14 10:14 UTC, randomroot approved these changes
🟢 **Работа принята:**

Все необходимые правки были внесены, код улучшен согласно рекомендациям, критических замечаний больше не имеется, **так держать**👍

Перед слитием ветки в `main` рекомендую удалить неиспользуемый закомментированный код, а также воспользоваться функцией `fetchWithRefresh` в остальных методах, где есть токен - **отправка заказа** и **обновление данных пользователя**

**Желаю вам хорошего дня и успехов в дальнейшем обучении**! 🐈

2023-01-14 10:14 UTC, randomroot commented on src/services/actions/userActions.js
> +      //  const res = await fetch(`${BASE_URL}/auth/user`, {
🟡 **Можно улучшить:**

Рекомендую удалить неиспользуемый закомментированный код

2023-01-21 20:26 UTC, merged